# Generated by Django 5.0.7 on 2024-08-05 16:25

import acs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0006_mymodel_alter_student_id_alter_tracker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='blood_group',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(upload_to=acs.models.MyModel.get_upload_path),
        ),
    ]
