# Generated by Django 5.0.7 on 2024-09-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0007_mymodel_blood_group_alter_mymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='blood_pressure',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='bmi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='hormonal_issue',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='sex',
            field=models.CharField(default='', max_length=5),
        ),
    ]
