# Generated by Django 5.1.3 on 2024-11-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs', '0008_mymodel_blood_pressure_mymodel_bmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='blood_group',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='blood_pressure',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='hormonal_issue',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='sex',
            field=models.CharField(default='', max_length=25),
        ),
    ]
